// src/main/webapp/app/entities/prepayment-data/prepayment-data-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './prepayment-data.reducer';
import { IPrepaymentData } from 'app/shared/model/prepayment-data.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPrepaymentDataDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PrepaymentDataDetail = (props: IPrepaymentDataDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { prepaymentDataEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          PrepaymentData [<b>{prepaymentDataEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="accountName">Account Name</span>
          </dt>
          <dd>{prepaymentDataEntity.accountName}</dd>
          <dt>
            <span id="description">Description</span>
          </dt>
          <dd>{prepaymentDataEntity.description}</dd>
          <dt>
            <span id="accountNumber">Account Number</span>
          </dt>
          <dd>{prepaymentDataEntity.accountNumber}</dd>
          <dt>
            <span id="expenseAccountNumber">Expense Account Number</span>
          </dt>
          <dd>{prepaymentDataEntity.expenseAccountNumber}</dd>
          <dt>
            <span id="prepaymentNumber">Prepayment Number</span>
          </dt>
          <dd>{prepaymentDataEntity.prepaymentNumber}</dd>
          <dt>
            <span id="prepaymentDate">Prepayment Date</span>
          </dt>
          <dd>
            {prepaymentDataEntity.prepaymentDate ? (
              <TextFormat value={prepaymentDataEntity.prepaymentDate} type="date" format={APP_LOCAL_DATE_FORMAT} />
            ) : null}
          </dd>
          <dt>
            <span id="prepaymentAmount">Prepayment Amount</span>
          </dt>
          <dd>{prepaymentDataEntity.prepaymentAmount}</dd>
          <dt>
            <span id="prepaymentPeriods">Prepayment Periods</span>
          </dt>
          <dd>{prepaymentDataEntity.prepaymentPeriods}</dd>
          <dt>
            <span id="uploadToken">Upload Token</span>
          </dt>
          <dd>{prepaymentDataEntity.uploadToken}</dd>
        </dl>
        <Button tag={Link} to="/prepayment-data" replace color="info">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/prepayment-data/${prepaymentDataEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ prepaymentData }: IRootState) => ({
  prepaymentDataEntity: prepaymentData.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PrepaymentDataDetail);

// src/main/webapp/app/entities/prepayment-data/prepayment-data-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IPrepaymentData } from 'app/shared/model/prepayment-data.model';

@Component({
  selector: 'gha-prepayment-data-detail',
  templateUrl: './prepayment-data-detail.component.html',
})
export class PrepaymentDataDetailComponent implements OnInit {
  prepaymentData: IPrepaymentData | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ prepaymentData }) => (this.prepaymentData = prepaymentData));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="prepaymentData">
            <h2><span>Prepayment Data</span> {{ prepaymentData.id }}</h2>

            <hr>

            <gha-alert-error></gha-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span>Account Name</span></dt>
                <dd>
                    <span>{{ prepaymentData.accountName }}</span>
                </dd>
                <dt><span>Description</span></dt>
                <dd>
                    <span>{{ prepaymentData.description }}</span>
                </dd>
                <dt><span>Account Number</span></dt>
                <dd>
                    <span>{{ prepaymentData.accountNumber }}</span>
                </dd>
                <dt><span>Expense Account Number</span></dt>
                <dd>
                    <span>{{ prepaymentData.expenseAccountNumber }}</span>
                </dd>
                <dt><span>Prepayment Number</span></dt>
                <dd>
                    <span>{{ prepaymentData.prepaymentNumber }}</span>
                </dd>
                <dt><span>Prepayment Date</span></dt>
                <dd>
                    <span>{{ prepaymentData.prepaymentDate }}</span>
                </dd>
                <dt><span>Prepayment Amount</span></dt>
                <dd>
                    <span>{{ prepaymentData.prepaymentAmount }}</span>
                </dd>
                <dt><span>Prepayment Periods</span></dt>
                <dd>
                    <span>{{ prepaymentData.prepaymentPeriods }}</span>
                </dd>
                <dt><span>Upload Token</span></dt>
                <dd>
                    <span>{{ prepaymentData.uploadToken }}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/prepayment-data', prepaymentData.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
            </button>
        </div>
    </div>
</div>
