// src/main/webapp/app/entities/compilation-request/compilation-request-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { ICompilationRequest, CompilationRequest } from 'app/shared/model/compilation-request.model';
import { CompilationRequestService } from './compilation-request.service';

@Component({
  selector: 'gha-compilation-request-update',
  templateUrl: './compilation-request-update.component.html',
})
export class CompilationRequestUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    description: [],
    fileUploadId: [],
    compilationStatus: [],
    compilationType: [],
    compilationToken: [],
  });

  constructor(
    protected compilationRequestService: CompilationRequestService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ compilationRequest }) => {
      this.updateForm(compilationRequest);
    });
  }

  updateForm(compilationRequest: ICompilationRequest): void {
    this.editForm.patchValue({
      id: compilationRequest.id,
      description: compilationRequest.description,
      fileUploadId: compilationRequest.fileUploadId,
      compilationStatus: compilationRequest.compilationStatus,
      compilationType: compilationRequest.compilationType,
      compilationToken: compilationRequest.compilationToken,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const compilationRequest = this.createFromForm();
    if (compilationRequest.id !== undefined) {
      this.subscribeToSaveResponse(this.compilationRequestService.update(compilationRequest));
    } else {
      this.subscribeToSaveResponse(this.compilationRequestService.create(compilationRequest));
    }
  }

  private createFromForm(): ICompilationRequest {
    return {
      ...new CompilationRequest(),
      id: this.editForm.get(['id'])!.value,
      description: this.editForm.get(['description'])!.value,
      fileUploadId: this.editForm.get(['fileUploadId'])!.value,
      compilationStatus: this.editForm.get(['compilationStatus'])!.value,
      compilationType: this.editForm.get(['compilationType'])!.value,
      compilationToken: this.editForm.get(['compilationToken'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICompilationRequest>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="gha-compilation-request-heading">Create or edit a Compilation Request</h2>

            <div>
                <gha-alert-error></gha-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_description">Description</label>
                    <input type="text" class="form-control" name="description" id="field_description"
                           formControlName="description"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_fileUploadId">File Upload Id</label>
                    <input type="number" class="form-control" name="fileUploadId" id="field_fileUploadId"
                           formControlName="fileUploadId"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_compilationStatus">Compilation Status</label>
                    <select class="form-control" name="compilationStatus" formControlName="compilationStatus" id="field_compilationStatus">
                        <option value="IN_PROGRESS">IN_PROGRESS</option>
                        <option value="COMPLETE">COMPLETE</option>
                        <option value="FAILED">FAILED</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_compilationType">Compilation Type</label>
                    <select class="form-control" name="compilationType" formControlName="compilationType" id="field_compilationType">
                        <option value="AMORTIZATION_ENTRY_COMPILATION">AMORTIZATION_ENTRY_COMPILATION</option>
                        <option value="PREPAYMENT_ENTRY_COMPILATION">PREPAYMENT_ENTRY_COMPILATION</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_compilationToken">Compilation Token</label>
                    <input type="text" class="form-control" name="compilationToken" id="field_compilationToken"
                           formControlName="compilationToken"/>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/compilation-request/compilation-request-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './compilation-request.reducer';
import { ICompilationRequest } from 'app/shared/model/compilation-request.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ICompilationRequestUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const CompilationRequestUpdate = (props: ICompilationRequestUpdateProps) => {
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { compilationRequestEntity, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/compilation-request' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...compilationRequestEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="prepaymentsDevApp.compilationRequest.home.createOrEditLabel">Create or edit a CompilationRequest</h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : compilationRequestEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="compilation-request-id">ID</Label>
                  <AvInput id="compilation-request-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="descriptionLabel" for="compilation-request-description">
                  Description
                </Label>
                <AvField id="compilation-request-description" type="text" name="description" />
              </AvGroup>
              <AvGroup>
                <Label id="fileUploadIdLabel" for="compilation-request-fileUploadId">
                  File Upload Id
                </Label>
                <AvField id="compilation-request-fileUploadId" type="string" className="form-control" name="fileUploadId" />
              </AvGroup>
              <AvGroup>
                <Label id="compilationStatusLabel" for="compilation-request-compilationStatus">
                  Compilation Status
                </Label>
                <AvInput
                  id="compilation-request-compilationStatus"
                  type="select"
                  className="form-control"
                  name="compilationStatus"
                  value={(!isNew && compilationRequestEntity.compilationStatus) || 'IN_PROGRESS'}
                >
                  <option value="IN_PROGRESS">IN_PROGRESS</option>
                  <option value="COMPLETE">COMPLETE</option>
                  <option value="FAILED">FAILED</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="compilationTypeLabel" for="compilation-request-compilationType">
                  Compilation Type
                </Label>
                <AvInput
                  id="compilation-request-compilationType"
                  type="select"
                  className="form-control"
                  name="compilationType"
                  value={(!isNew && compilationRequestEntity.compilationType) || 'AMORTIZATION_ENTRY_COMPILATION'}
                >
                  <option value="AMORTIZATION_ENTRY_COMPILATION">AMORTIZATION_ENTRY_COMPILATION</option>
                  <option value="PREPAYMENT_ENTRY_COMPILATION">PREPAYMENT_ENTRY_COMPILATION</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="compilationTokenLabel" for="compilation-request-compilationToken">
                  Compilation Token
                </Label>
                <AvField id="compilation-request-compilationToken" type="text" name="compilationToken" />
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/compilation-request" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  compilationRequestEntity: storeState.compilationRequest.entity,
  loading: storeState.compilationRequest.loading,
  updating: storeState.compilationRequest.updating,
  updateSuccess: storeState.compilationRequest.updateSuccess,
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(CompilationRequestUpdate);
