// src/main/webapp/app/entities/preps/preps-file-type/preps-file-type-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { JhiDataUtils } from 'ng-jhipster';

import { IPrepsFileType } from 'app/shared/model/preps/preps-file-type.model';

@Component({
  selector: 'gha-preps-file-type-detail',
  templateUrl: './preps-file-type-detail.component.html',
})
export class PrepsFileTypeDetailComponent implements OnInit {
  prepsFileType: IPrepsFileType | null = null;

  constructor(protected dataUtils: JhiDataUtils, protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ prepsFileType }) => (this.prepsFileType = prepsFileType));
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(contentType = '', base64String: string): void {
    this.dataUtils.openFile(contentType, base64String);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="prepsFileType">
            <h2><span>Preps File Type</span> {{ prepsFileType.id }}</h2>

            <hr>

            <gha-alert-error></gha-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span>Preps File Type Name</span></dt>
                <dd>
                    <span>{{ prepsFileType.prepsFileTypeName }}</span>
                </dd>
                <dt><span>Preps File Medium Type</span></dt>
                <dd>
                    <span>{{ prepsFileType.prepsFileMediumType }}</span>
                </dd>
                <dt><span>Description</span></dt>
                <dd>
                    <span>{{ prepsFileType.description }}</span>
                </dd>
                <dt><span>File Template</span></dt>
                <dd>
                    <div *ngIf="prepsFileType.fileTemplate">
                        <a (click)="openFile(prepsFileType.fileTemplateContentType, prepsFileType.fileTemplate)">open</a>
                        {{ prepsFileType.fileTemplateContentType }}, {{ byteSize(prepsFileType.fileTemplate) }}
                    </div>
                </dd>
                <dt><span>Prepsfile Type</span></dt>
                <dd>
                    <span>{{ prepsFileType.prepsfileType }}</span>
                </dd>
                <dt><span>Prepsfile Delete Process Type</span></dt>
                <dd>
                    <span>{{ prepsFileType.prepsfileDeleteProcessType }}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/preps-file-type', prepsFileType.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/preps/preps-file-type/preps-file-type-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { ICrudGetAction, openFile, byteSize } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './preps-file-type.reducer';
import { IPrepsFileType } from 'app/shared/model/preps/preps-file-type.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPrepsFileTypeDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PrepsFileTypeDetail = (props: IPrepsFileTypeDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { prepsFileTypeEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          PrepsFileType [<b>{prepsFileTypeEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="prepsFileTypeName">Preps File Type Name</span>
          </dt>
          <dd>{prepsFileTypeEntity.prepsFileTypeName}</dd>
          <dt>
            <span id="prepsFileMediumType">Preps File Medium Type</span>
          </dt>
          <dd>{prepsFileTypeEntity.prepsFileMediumType}</dd>
          <dt>
            <span id="description">Description</span>
          </dt>
          <dd>{prepsFileTypeEntity.description}</dd>
          <dt>
            <span id="fileTemplate">File Template</span>
          </dt>
          <dd>
            {prepsFileTypeEntity.fileTemplate ? (
              <div>
                {prepsFileTypeEntity.fileTemplateContentType ? (
                  <a onClick={openFile(prepsFileTypeEntity.fileTemplateContentType, prepsFileTypeEntity.fileTemplate)}>Open&nbsp;</a>
                ) : null}
                <span>
                  {prepsFileTypeEntity.fileTemplateContentType}, {byteSize(prepsFileTypeEntity.fileTemplate)}
                </span>
              </div>
            ) : null}
          </dd>
          <dt>
            <span id="prepsfileType">Prepsfile Type</span>
          </dt>
          <dd>{prepsFileTypeEntity.prepsfileType}</dd>
          <dt>
            <span id="prepsfileDeleteProcessType">Prepsfile Delete Process Type</span>
          </dt>
          <dd>{prepsFileTypeEntity.prepsfileDeleteProcessType}</dd>
        </dl>
        <Button tag={Link} to="/preps-file-type" replace color="info">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/preps-file-type/${prepsFileTypeEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ prepsFileType }: IRootState) => ({
  prepsFileTypeEntity: prepsFileType.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PrepsFileTypeDetail);
