// src/main/webapp/app/entities/preps/preps-file-type/preps-file-type-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { JhiDataUtils, JhiFileLoadError, JhiEventManager, JhiEventWithContent } from 'ng-jhipster';

import { IPrepsFileType, PrepsFileType } from 'app/shared/model/preps/preps-file-type.model';
import { PrepsFileTypeService } from './preps-file-type.service';
import { AlertError } from 'app/shared/alert/alert-error.model';

@Component({
  selector: 'gha-preps-file-type-update',
  templateUrl: './preps-file-type-update.component.html',
})
export class PrepsFileTypeUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    prepsFileTypeName: [null, [Validators.required]],
    prepsFileMediumType: [null, [Validators.required]],
    description: [],
    fileTemplate: [],
    fileTemplateContentType: [],
    prepsfileType: [],
    prepsfileDeleteProcessType: [],
  });

  constructor(
    protected dataUtils: JhiDataUtils,
    protected eventManager: JhiEventManager,
    protected prepsFileTypeService: PrepsFileTypeService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ prepsFileType }) => {
      this.updateForm(prepsFileType);
    });
  }

  updateForm(prepsFileType: IPrepsFileType): void {
    this.editForm.patchValue({
      id: prepsFileType.id,
      prepsFileTypeName: prepsFileType.prepsFileTypeName,
      prepsFileMediumType: prepsFileType.prepsFileMediumType,
      description: prepsFileType.description,
      fileTemplate: prepsFileType.fileTemplate,
      fileTemplateContentType: prepsFileType.fileTemplateContentType,
      prepsfileType: prepsFileType.prepsfileType,
      prepsfileDeleteProcessType: prepsFileType.prepsfileDeleteProcessType,
    });
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(contentType: string, base64String: string): void {
    this.dataUtils.openFile(contentType, base64String);
  }

  setFileData(event: any, field: string, isImage: boolean): void {
    this.dataUtils.loadFileToForm(event, this.editForm, field, isImage).subscribe(null, (err: JhiFileLoadError) => {
      this.eventManager.broadcast(
        new JhiEventWithContent<AlertError>('prepaymentsDeveloperApp.error', { message: err.message })
      );
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const prepsFileType = this.createFromForm();
    if (prepsFileType.id !== undefined) {
      this.subscribeToSaveResponse(this.prepsFileTypeService.update(prepsFileType));
    } else {
      this.subscribeToSaveResponse(this.prepsFileTypeService.create(prepsFileType));
    }
  }

  private createFromForm(): IPrepsFileType {
    return {
      ...new PrepsFileType(),
      id: this.editForm.get(['id'])!.value,
      prepsFileTypeName: this.editForm.get(['prepsFileTypeName'])!.value,
      prepsFileMediumType: this.editForm.get(['prepsFileMediumType'])!.value,
      description: this.editForm.get(['description'])!.value,
      fileTemplateContentType: this.editForm.get(['fileTemplateContentType'])!.value,
      fileTemplate: this.editForm.get(['fileTemplate'])!.value,
      prepsfileType: this.editForm.get(['prepsfileType'])!.value,
      prepsfileDeleteProcessType: this.editForm.get(['prepsfileDeleteProcessType'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IPrepsFileType>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="gha-preps-file-type-heading">Create or edit a Preps File Type</h2>

            <div>
                <gha-alert-error></gha-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_prepsFileTypeName">Preps File Type Name</label>
                    <input type="text" class="form-control" name="prepsFileTypeName" id="field_prepsFileTypeName"
                           formControlName="prepsFileTypeName"/>
                    <div *ngIf="editForm.get('prepsFileTypeName')!.invalid && (editForm.get('prepsFileTypeName')!.dirty || editForm.get('prepsFileTypeName')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('prepsFileTypeName')?.errors?.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_prepsFileMediumType">Preps File Medium Type</label>
                    <select class="form-control" name="prepsFileMediumType" formControlName="prepsFileMediumType" id="field_prepsFileMediumType">
                        <option value="EXCEL">EXCEL</option>
                        <option value="EXCEL_XLS">EXCEL_XLS</option>
                        <option value="EXCEL_XLSX">EXCEL_XLSX</option>
                        <option value="EXCEL_XLSB">EXCEL_XLSB</option>
                        <option value="EXCEL_CSV">EXCEL_CSV</option>
                        <option value="EXCEL_XML">EXCEL_XML</option>
                        <option value="PDF">PDF</option>
                        <option value="POWERPOINT">POWERPOINT</option>
                        <option value="DOC">DOC</option>
                        <option value="TEXT">TEXT</option>
                        <option value="JSON">JSON</option>
                        <option value="HTML5">HTML5</option>
                    </select>
                    <div *ngIf="editForm.get('prepsFileMediumType')!.invalid && (editForm.get('prepsFileMediumType')!.dirty || editForm.get('prepsFileMediumType')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('prepsFileMediumType')?.errors?.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_description">Description</label>
                    <input type="text" class="form-control" name="description" id="field_description"
                           formControlName="description"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_fileTemplate">File Template</label>
                    <div>
                        <div *ngIf="editForm.get('fileTemplate')!.value" class="form-text text-danger clearfix">
                            <a class="pull-left" (click)="openFile(editForm.get('fileTemplateContentType')!.value, editForm.get('fileTemplate')!.value)">open</a><br>
                            <span class="pull-left">{{ editForm.get('fileTemplateContentType')!.value }}, {{ byteSize(editForm.get('fileTemplate')!.value) }}</span>
                            <button type="button" (click)="editForm.patchValue({fileTemplate: null});editForm.patchValue({fileTemplateContentType: null});"
                                    class="btn btn-secondary btn-xs pull-right">
                                <fa-icon icon="times"></fa-icon>
                            </button>
                        </div>
                        <input type="file" id="file_fileTemplate" (change)="setFileData($event, 'fileTemplate', false)"/>
                    </div>
                    <input type="hidden" class="form-control" name="fileTemplate" id="field_fileTemplate"
                           formControlName="fileTemplate"/>
                    <input type="hidden" class="form-control" name="fileTemplateContentType" id="field_fileTemplateContentType"
                           formControlName="fileTemplateContentType" />
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_prepsfileType">Prepsfile Type</label>
                    <select class="form-control" name="prepsfileType" formControlName="prepsfileType" id="field_prepsfileType">
                        <option value="CURRENCY_LIST">CURRENCY_LIST</option>
                        <option value="PREPAYMENT_DATA">PREPAYMENT_DATA</option>
                        <option value="PREPAYMENT_ENTRY">PREPAYMENT_ENTRY</option>
                        <option value="AMORTIZATION_ENTRY">AMORTIZATION_ENTRY</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_prepsfileDeleteProcessType">Prepsfile Delete Process Type</label>
                    <select class="form-control" name="prepsfileDeleteProcessType" formControlName="prepsfileDeleteProcessType" id="field_prepsfileDeleteProcessType">
                        <option value="DELETE_PREPAYMENT_DATA">DELETE_PREPAYMENT_DATA</option>
                        <option value="DELETE_PREPAYMENT_ENTRY">DELETE_PREPAYMENT_ENTRY</option>
                        <option value="DELETE_AMORTIZATION_ENTRY">DELETE_AMORTIZATION_ENTRY</option>
                    </select>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/preps/preps-file-type/preps-file-type-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { ICrudGetAction, ICrudGetAllAction, setFileData, openFile, byteSize, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, setBlob, reset } from './preps-file-type.reducer';
import { IPrepsFileType } from 'app/shared/model/preps/preps-file-type.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IPrepsFileTypeUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PrepsFileTypeUpdate = (props: IPrepsFileTypeUpdateProps) => {
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { prepsFileTypeEntity, loading, updating } = props;

  const { fileTemplate, fileTemplateContentType } = prepsFileTypeEntity;

  const handleClose = () => {
    props.history.push('/preps-file-type' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  const onBlobChange = (isAnImage, name) => event => {
    setFileData(event, (contentType, data) => props.setBlob(name, data, contentType), isAnImage);
  };

  const clearBlob = name => () => {
    props.setBlob(name, undefined, undefined);
  };

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...prepsFileTypeEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="prepaymentsDevApp.prepsPrepsFileType.home.createOrEditLabel">Create or edit a PrepsFileType</h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : prepsFileTypeEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="preps-file-type-id">ID</Label>
                  <AvInput id="preps-file-type-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="prepsFileTypeNameLabel" for="preps-file-type-prepsFileTypeName">
                  Preps File Type Name
                </Label>
                <AvField
                  id="preps-file-type-prepsFileTypeName"
                  type="text"
                  name="prepsFileTypeName"
                  validate={{
                    required: { value: true, errorMessage: 'This field is required.' },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="prepsFileMediumTypeLabel" for="preps-file-type-prepsFileMediumType">
                  Preps File Medium Type
                </Label>
                <AvInput
                  id="preps-file-type-prepsFileMediumType"
                  type="select"
                  className="form-control"
                  name="prepsFileMediumType"
                  value={(!isNew && prepsFileTypeEntity.prepsFileMediumType) || 'EXCEL'}
                >
                  <option value="EXCEL">EXCEL</option>
                  <option value="EXCEL_XLS">EXCEL_XLS</option>
                  <option value="EXCEL_XLSX">EXCEL_XLSX</option>
                  <option value="EXCEL_XLSB">EXCEL_XLSB</option>
                  <option value="EXCEL_CSV">EXCEL_CSV</option>
                  <option value="EXCEL_XML">EXCEL_XML</option>
                  <option value="PDF">PDF</option>
                  <option value="POWERPOINT">POWERPOINT</option>
                  <option value="DOC">DOC</option>
                  <option value="TEXT">TEXT</option>
                  <option value="JSON">JSON</option>
                  <option value="HTML5">HTML5</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="descriptionLabel" for="preps-file-type-description">
                  Description
                </Label>
                <AvField id="preps-file-type-description" type="text" name="description" />
              </AvGroup>
              <AvGroup>
                <AvGroup>
                  <Label id="fileTemplateLabel" for="fileTemplate">
                    File Template
                  </Label>
                  <br />
                  {fileTemplate ? (
                    <div>
                      {fileTemplateContentType ? <a onClick={openFile(fileTemplateContentType, fileTemplate)}>Open</a> : null}
                      <br />
                      <Row>
                        <Col md="11">
                          <span>
                            {fileTemplateContentType}, {byteSize(fileTemplate)}
                          </span>
                        </Col>
                        <Col md="1">
                          <Button color="danger" onClick={clearBlob('fileTemplate')}>
                            <FontAwesomeIcon icon="times-circle" />
                          </Button>
                        </Col>
                      </Row>
                    </div>
                  ) : null}
                  <input id="file_fileTemplate" type="file" onChange={onBlobChange(false, 'fileTemplate')} />
                  <AvInput type="hidden" name="fileTemplate" value={fileTemplate} />
                </AvGroup>
              </AvGroup>
              <AvGroup>
                <Label id="prepsfileTypeLabel" for="preps-file-type-prepsfileType">
                  Prepsfile Type
                </Label>
                <AvInput
                  id="preps-file-type-prepsfileType"
                  type="select"
                  className="form-control"
                  name="prepsfileType"
                  value={(!isNew && prepsFileTypeEntity.prepsfileType) || 'CURRENCY_LIST'}
                >
                  <option value="CURRENCY_LIST">CURRENCY_LIST</option>
                  <option value="PREPAYMENT_DATA">PREPAYMENT_DATA</option>
                  <option value="PREPAYMENT_ENTRY">PREPAYMENT_ENTRY</option>
                  <option value="AMORTIZATION_ENTRY">AMORTIZATION_ENTRY</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="prepsfileDeleteProcessTypeLabel" for="preps-file-type-prepsfileDeleteProcessType">
                  Prepsfile Delete Process Type
                </Label>
                <AvInput
                  id="preps-file-type-prepsfileDeleteProcessType"
                  type="select"
                  className="form-control"
                  name="prepsfileDeleteProcessType"
                  value={(!isNew && prepsFileTypeEntity.prepsfileDeleteProcessType) || 'DELETE_PREPAYMENT_DATA'}
                >
                  <option value="DELETE_PREPAYMENT_DATA">DELETE_PREPAYMENT_DATA</option>
                  <option value="DELETE_PREPAYMENT_ENTRY">DELETE_PREPAYMENT_ENTRY</option>
                  <option value="DELETE_AMORTIZATION_ENTRY">DELETE_AMORTIZATION_ENTRY</option>
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/preps-file-type" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  prepsFileTypeEntity: storeState.prepsFileType.entity,
  loading: storeState.prepsFileType.loading,
  updating: storeState.prepsFileType.updating,
  updateSuccess: storeState.prepsFileType.updateSuccess,
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  setBlob,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PrepsFileTypeUpdate);
