// src/main/webapp/app/entities/preps/preps-file-type/preps-file-type.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { openFile, byteSize, ICrudGetAllAction, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './preps-file-type.reducer';
import { IPrepsFileType } from 'app/shared/model/preps/preps-file-type.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IPrepsFileTypeProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const PrepsFileType = (props: IPrepsFileTypeProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const { prepsFileTypeList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="preps-file-type-heading">
        Preps File Types
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp; Create new Preps File Type
        </Link>
      </h2>
      <div className="table-responsive">
        {prepsFileTypeList && prepsFileTypeList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  ID <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('prepsFileTypeName')}>
                  Preps File Type Name <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('prepsFileMediumType')}>
                  Preps File Medium Type <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('description')}>
                  Description <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('fileTemplate')}>
                  File Template <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('prepsfileType')}>
                  Prepsfile Type <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('prepsfileDeleteProcessType')}>
                  Prepsfile Delete Process Type <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {prepsFileTypeList.map((prepsFileType, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${prepsFileType.id}`} color="link" size="sm">
                      {prepsFileType.id}
                    </Button>
                  </td>
                  <td>{prepsFileType.prepsFileTypeName}</td>
                  <td>{prepsFileType.prepsFileMediumType}</td>
                  <td>{prepsFileType.description}</td>
                  <td>
                    {prepsFileType.fileTemplate ? (
                      <div>
                        {prepsFileType.fileTemplateContentType ? (
                          <a onClick={openFile(prepsFileType.fileTemplateContentType, prepsFileType.fileTemplate)}>Open &nbsp;</a>
                        ) : null}
                        <span>
                          {prepsFileType.fileTemplateContentType}, {byteSize(prepsFileType.fileTemplate)}
                        </span>
                      </div>
                    ) : null}
                  </td>
                  <td>{prepsFileType.prepsfileType}</td>
                  <td>{prepsFileType.prepsfileDeleteProcessType}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${prepsFileType.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${prepsFileType.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${prepsFileType.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Preps File Types found</div>
        )}
      </div>
      {props.totalItems ? (
        <div className={prepsFileTypeList && prepsFileTypeList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ prepsFileType }: IRootState) => ({
  prepsFileTypeList: prepsFileType.entities,
  loading: prepsFileType.loading,
  totalItems: prepsFileType.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PrepsFileType);

// src/main/webapp/app/entities/preps/preps-file-type/preps-file-type.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, ParamMap, Router, Data } from '@angular/router';
import { Subscription, combineLatest } from 'rxjs';
import { JhiEventManager, JhiDataUtils } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IPrepsFileType } from 'app/shared/model/preps/preps-file-type.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { PrepsFileTypeService } from './preps-file-type.service';
import { PrepsFileTypeDeleteDialogComponent } from './preps-file-type-delete-dialog.component';

@Component({
  selector: 'gha-preps-file-type',
  templateUrl: './preps-file-type.component.html',
})
export class PrepsFileTypeComponent implements OnInit, OnDestroy {
  prepsFileTypes?: IPrepsFileType[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected prepsFileTypeService: PrepsFileTypeService,
    protected activatedRoute: ActivatedRoute,
    protected dataUtils: JhiDataUtils,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number, dontNavigate?: boolean): void {
    const pageToLoad: number = page || this.page || 1;

    this.prepsFileTypeService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<IPrepsFileType[]>) => this.onSuccess(res.body, res.headers, pageToLoad, !dontNavigate),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.handleNavigation();
    this.registerChangeInPrepsFileTypes();
  }

  protected handleNavigation(): void {
    combineLatest(this.activatedRoute.data, this.activatedRoute.queryParamMap, (data: Data, params: ParamMap) => {
      const page = params.get('page');
      const pageNumber = page !== null ? +page : 1;
      const sort = (params.get('sort') ?? data['defaultSort']).split(',');
      const predicate = sort[0];
      const ascending = sort[1] === 'asc';
      if (pageNumber !== this.page || predicate !== this.predicate || ascending !== this.ascending) {
        this.predicate = predicate;
        this.ascending = ascending;
        this.loadPage(pageNumber, true);
      }
    }).subscribe();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IPrepsFileType): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(contentType = '', base64String: string): void {
    return this.dataUtils.openFile(contentType, base64String);
  }

  registerChangeInPrepsFileTypes(): void {
    this.eventSubscriber = this.eventManager.subscribe('prepsFileTypeListModification', () => this.loadPage());
  }

  delete(prepsFileType: IPrepsFileType): void {
    const modalRef = this.modalService.open(PrepsFileTypeDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.prepsFileType = prepsFileType;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: IPrepsFileType[] | null, headers: HttpHeaders, page: number, navigate: boolean): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    if (navigate) {
      this.router.navigate(['/preps-file-type'], {
        queryParams: {
          page: this.page,
          size: this.itemsPerPage,
          sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc'),
        },
      });
    }
    this.prepsFileTypes = data || [];
    this.ngbPaginationPage = this.page;
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page ?? 1;
  }
}

<div>
    <h2 id="page-heading">
        <span>Preps File Types</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-preps-file-type" [routerLink]="['/preps-file-type/new']">
            <fa-icon icon="plus"></fa-icon>
            <span>
            Create a new Preps File Type
            </span>
        </button>
    </h2>

    <gha-alert-error></gha-alert-error>

    <gha-alert></gha-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="prepsFileTypes?.length === 0">
        <span>No prepsFileTypes found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="prepsFileTypes && prepsFileTypes.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span>ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="prepsFileTypeName"><span>Preps File Type Name</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="prepsFileMediumType"><span>Preps File Medium Type</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="description"><span>Description</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="fileTemplate"><span>File Template</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="prepsfileType"><span>Prepsfile Type</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="prepsfileDeleteProcessType"><span>Prepsfile Delete Process Type</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let prepsFileType of prepsFileTypes ;trackBy: trackId">
                    <td><a [routerLink]="['/preps-file-type', prepsFileType.id, 'view']">{{ prepsFileType.id }}</a></td>
                    <td>{{ prepsFileType.prepsFileTypeName }}</td>
                    <td>{{ prepsFileType.prepsFileMediumType }}</td>
                    <td>{{ prepsFileType.description }}</td>
                    <td>
                        <a *ngIf="prepsFileType.fileTemplate" (click)="openFile(prepsFileType.fileTemplateContentType, prepsFileType.fileTemplate)">open</a>
                        <span *ngIf="prepsFileType.fileTemplate">{{ prepsFileType.fileTemplateContentType }}, {{ byteSize(prepsFileType.fileTemplate) }}</span>
                    </td>
                    <td>{{ prepsFileType.prepsfileType }}</td>
                    <td>{{ prepsFileType.prepsfileDeleteProcessType }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/preps-file-type', prepsFileType.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/preps-file-type', prepsFileType.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(prepsFileType)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="prepsFileTypes && prepsFileTypes.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>
