// src/main/webapp/app/entities/preps/preps-message-token/preps-message-token-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IPrepsMessageToken } from 'app/shared/model/preps/preps-message-token.model';

@Component({
  selector: 'gha-preps-message-token-detail',
  templateUrl: './preps-message-token-detail.component.html',
})
export class PrepsMessageTokenDetailComponent implements OnInit {
  prepsMessageToken: IPrepsMessageToken | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ prepsMessageToken }) => (this.prepsMessageToken = prepsMessageToken));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="prepsMessageToken">
            <h2><span>Preps Message Token</span> {{ prepsMessageToken.id }}</h2>

            <hr>

            <gha-alert-error></gha-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span>Description</span></dt>
                <dd>
                    <span>{{ prepsMessageToken.description }}</span>
                </dd>
                <dt><span>Time Sent</span></dt>
                <dd>
                    <span>{{ prepsMessageToken.timeSent }}</span>
                </dd>
                <dt><span>Token Value</span></dt>
                <dd>
                    <span>{{ prepsMessageToken.tokenValue }}</span>
                </dd>
                <dt><span>Received</span></dt>
                <dd>
                    <span>{{ prepsMessageToken.received }}</span>
                </dd>
                <dt><span>Actioned</span></dt>
                <dd>
                    <span>{{ prepsMessageToken.actioned }}</span>
                </dd>
                <dt><span>Content Fully Enqueued</span></dt>
                <dd>
                    <span>{{ prepsMessageToken.contentFullyEnqueued }}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/preps-message-token', prepsMessageToken.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/preps/preps-message-token/preps-message-token-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './preps-message-token.reducer';
import { IPrepsMessageToken } from 'app/shared/model/preps/preps-message-token.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPrepsMessageTokenDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PrepsMessageTokenDetail = (props: IPrepsMessageTokenDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { prepsMessageTokenEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          PrepsMessageToken [<b>{prepsMessageTokenEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="description">Description</span>
          </dt>
          <dd>{prepsMessageTokenEntity.description}</dd>
          <dt>
            <span id="timeSent">Time Sent</span>
          </dt>
          <dd>{prepsMessageTokenEntity.timeSent}</dd>
          <dt>
            <span id="tokenValue">Token Value</span>
          </dt>
          <dd>{prepsMessageTokenEntity.tokenValue}</dd>
          <dt>
            <span id="received">Received</span>
          </dt>
          <dd>{prepsMessageTokenEntity.received ? 'true' : 'false'}</dd>
          <dt>
            <span id="actioned">Actioned</span>
          </dt>
          <dd>{prepsMessageTokenEntity.actioned ? 'true' : 'false'}</dd>
          <dt>
            <span id="contentFullyEnqueued">Content Fully Enqueued</span>
          </dt>
          <dd>{prepsMessageTokenEntity.contentFullyEnqueued ? 'true' : 'false'}</dd>
        </dl>
        <Button tag={Link} to="/preps-message-token" replace color="info">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/preps-message-token/${prepsMessageTokenEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ prepsMessageToken }: IRootState) => ({
  prepsMessageTokenEntity: prepsMessageToken.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PrepsMessageTokenDetail);
