// src/main/webapp/app/entities/preps/preps-message-token/preps-message-token-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './preps-message-token.reducer';
import { IPrepsMessageToken } from 'app/shared/model/preps/preps-message-token.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IPrepsMessageTokenUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PrepsMessageTokenUpdate = (props: IPrepsMessageTokenUpdateProps) => {
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { prepsMessageTokenEntity, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/preps-message-token' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...prepsMessageTokenEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="prepaymentsDevApp.prepsPrepsMessageToken.home.createOrEditLabel">Create or edit a PrepsMessageToken</h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : prepsMessageTokenEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="preps-message-token-id">ID</Label>
                  <AvInput id="preps-message-token-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="descriptionLabel" for="preps-message-token-description">
                  Description
                </Label>
                <AvField id="preps-message-token-description" type="text" name="description" />
              </AvGroup>
              <AvGroup>
                <Label id="timeSentLabel" for="preps-message-token-timeSent">
                  Time Sent
                </Label>
                <AvField
                  id="preps-message-token-timeSent"
                  type="string"
                  className="form-control"
                  name="timeSent"
                  validate={{
                    required: { value: true, errorMessage: 'This field is required.' },
                    number: { value: true, errorMessage: 'This field should be a number.' },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="tokenValueLabel" for="preps-message-token-tokenValue">
                  Token Value
                </Label>
                <AvField
                  id="preps-message-token-tokenValue"
                  type="text"
                  name="tokenValue"
                  validate={{
                    required: { value: true, errorMessage: 'This field is required.' },
                  }}
                />
              </AvGroup>
              <AvGroup check>
                <Label id="receivedLabel">
                  <AvInput id="preps-message-token-received" type="checkbox" className="form-check-input" name="received" />
                  Received
                </Label>
              </AvGroup>
              <AvGroup check>
                <Label id="actionedLabel">
                  <AvInput id="preps-message-token-actioned" type="checkbox" className="form-check-input" name="actioned" />
                  Actioned
                </Label>
              </AvGroup>
              <AvGroup check>
                <Label id="contentFullyEnqueuedLabel">
                  <AvInput
                    id="preps-message-token-contentFullyEnqueued"
                    type="checkbox"
                    className="form-check-input"
                    name="contentFullyEnqueued"
                  />
                  Content Fully Enqueued
                </Label>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/preps-message-token" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  prepsMessageTokenEntity: storeState.prepsMessageToken.entity,
  loading: storeState.prepsMessageToken.loading,
  updating: storeState.prepsMessageToken.updating,
  updateSuccess: storeState.prepsMessageToken.updateSuccess,
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PrepsMessageTokenUpdate);

// src/main/webapp/app/entities/preps/preps-message-token/preps-message-token-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IPrepsMessageToken, PrepsMessageToken } from 'app/shared/model/preps/preps-message-token.model';
import { PrepsMessageTokenService } from './preps-message-token.service';

@Component({
  selector: 'gha-preps-message-token-update',
  templateUrl: './preps-message-token-update.component.html',
})
export class PrepsMessageTokenUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    description: [],
    timeSent: [null, [Validators.required]],
    tokenValue: [null, [Validators.required]],
    received: [],
    actioned: [],
    contentFullyEnqueued: [],
  });

  constructor(
    protected prepsMessageTokenService: PrepsMessageTokenService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ prepsMessageToken }) => {
      this.updateForm(prepsMessageToken);
    });
  }

  updateForm(prepsMessageToken: IPrepsMessageToken): void {
    this.editForm.patchValue({
      id: prepsMessageToken.id,
      description: prepsMessageToken.description,
      timeSent: prepsMessageToken.timeSent,
      tokenValue: prepsMessageToken.tokenValue,
      received: prepsMessageToken.received,
      actioned: prepsMessageToken.actioned,
      contentFullyEnqueued: prepsMessageToken.contentFullyEnqueued,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const prepsMessageToken = this.createFromForm();
    if (prepsMessageToken.id !== undefined) {
      this.subscribeToSaveResponse(this.prepsMessageTokenService.update(prepsMessageToken));
    } else {
      this.subscribeToSaveResponse(this.prepsMessageTokenService.create(prepsMessageToken));
    }
  }

  private createFromForm(): IPrepsMessageToken {
    return {
      ...new PrepsMessageToken(),
      id: this.editForm.get(['id'])!.value,
      description: this.editForm.get(['description'])!.value,
      timeSent: this.editForm.get(['timeSent'])!.value,
      tokenValue: this.editForm.get(['tokenValue'])!.value,
      received: this.editForm.get(['received'])!.value,
      actioned: this.editForm.get(['actioned'])!.value,
      contentFullyEnqueued: this.editForm.get(['contentFullyEnqueued'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IPrepsMessageToken>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="gha-preps-message-token-heading">Create or edit a Preps Message Token</h2>

            <div>
                <gha-alert-error></gha-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_description">Description</label>
                    <input type="text" class="form-control" name="description" id="field_description"
                           formControlName="description"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_timeSent">Time Sent</label>
                    <input type="number" class="form-control" name="timeSent" id="field_timeSent"
                           formControlName="timeSent"/>
                    <div *ngIf="editForm.get('timeSent')!.invalid && (editForm.get('timeSent')!.dirty || editForm.get('timeSent')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('timeSent')?.errors?.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('timeSent')?.errors?.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_tokenValue">Token Value</label>
                    <input type="text" class="form-control" name="tokenValue" id="field_tokenValue"
                           formControlName="tokenValue"/>
                    <div *ngIf="editForm.get('tokenValue')!.invalid && (editForm.get('tokenValue')!.dirty || editForm.get('tokenValue')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('tokenValue')?.errors?.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_received">Received</label>
                    <input type="checkbox" class="form-control" name="received" id="field_received"
                           formControlName="received"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_actioned">Actioned</label>
                    <input type="checkbox" class="form-control" name="actioned" id="field_actioned"
                           formControlName="actioned"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_contentFullyEnqueued">Content Fully Enqueued</label>
                    <input type="checkbox" class="form-control" name="contentFullyEnqueued" id="field_contentFullyEnqueued"
                           formControlName="contentFullyEnqueued"/>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
