// src/main/webapp/app/entities/preps/preps-message-token/preps-message-token.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, ParamMap, Router, Data } from '@angular/router';
import { Subscription, combineLatest } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IPrepsMessageToken } from 'app/shared/model/preps/preps-message-token.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { PrepsMessageTokenService } from './preps-message-token.service';
import { PrepsMessageTokenDeleteDialogComponent } from './preps-message-token-delete-dialog.component';

@Component({
  selector: 'gha-preps-message-token',
  templateUrl: './preps-message-token.component.html',
})
export class PrepsMessageTokenComponent implements OnInit, OnDestroy {
  prepsMessageTokens?: IPrepsMessageToken[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected prepsMessageTokenService: PrepsMessageTokenService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number, dontNavigate?: boolean): void {
    const pageToLoad: number = page || this.page || 1;

    this.prepsMessageTokenService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<IPrepsMessageToken[]>) => this.onSuccess(res.body, res.headers, pageToLoad, !dontNavigate),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.handleNavigation();
    this.registerChangeInPrepsMessageTokens();
  }

  protected handleNavigation(): void {
    combineLatest(this.activatedRoute.data, this.activatedRoute.queryParamMap, (data: Data, params: ParamMap) => {
      const page = params.get('page');
      const pageNumber = page !== null ? +page : 1;
      const sort = (params.get('sort') ?? data['defaultSort']).split(',');
      const predicate = sort[0];
      const ascending = sort[1] === 'asc';
      if (pageNumber !== this.page || predicate !== this.predicate || ascending !== this.ascending) {
        this.predicate = predicate;
        this.ascending = ascending;
        this.loadPage(pageNumber, true);
      }
    }).subscribe();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IPrepsMessageToken): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInPrepsMessageTokens(): void {
    this.eventSubscriber = this.eventManager.subscribe('prepsMessageTokenListModification', () => this.loadPage());
  }

  delete(prepsMessageToken: IPrepsMessageToken): void {
    const modalRef = this.modalService.open(PrepsMessageTokenDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.prepsMessageToken = prepsMessageToken;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: IPrepsMessageToken[] | null, headers: HttpHeaders, page: number, navigate: boolean): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    if (navigate) {
      this.router.navigate(['/preps-message-token'], {
        queryParams: {
          page: this.page,
          size: this.itemsPerPage,
          sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc'),
        },
      });
    }
    this.prepsMessageTokens = data || [];
    this.ngbPaginationPage = this.page;
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page ?? 1;
  }
}

<div>
    <h2 id="page-heading">
        <span>Preps Message Tokens</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-preps-message-token" [routerLink]="['/preps-message-token/new']">
            <fa-icon icon="plus"></fa-icon>
            <span>
            Create a new Preps Message Token
            </span>
        </button>
    </h2>

    <gha-alert-error></gha-alert-error>

    <gha-alert></gha-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="prepsMessageTokens?.length === 0">
        <span>No prepsMessageTokens found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="prepsMessageTokens && prepsMessageTokens.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span>ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="description"><span>Description</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="timeSent"><span>Time Sent</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="tokenValue"><span>Token Value</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="received"><span>Received</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="actioned"><span>Actioned</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="contentFullyEnqueued"><span>Content Fully Enqueued</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let prepsMessageToken of prepsMessageTokens ;trackBy: trackId">
                    <td><a [routerLink]="['/preps-message-token', prepsMessageToken.id, 'view']">{{ prepsMessageToken.id }}</a></td>
                    <td>{{ prepsMessageToken.description }}</td>
                    <td>{{ prepsMessageToken.timeSent }}</td>
                    <td>{{ prepsMessageToken.tokenValue }}</td>
                    <td>{{ prepsMessageToken.received }}</td>
                    <td>{{ prepsMessageToken.actioned }}</td>
                    <td>{{ prepsMessageToken.contentFullyEnqueued }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/preps-message-token', prepsMessageToken.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/preps-message-token', prepsMessageToken.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(prepsMessageToken)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="prepsMessageTokens && prepsMessageTokens.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/preps/preps-message-token/preps-message-token.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { ICrudGetAllAction, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './preps-message-token.reducer';
import { IPrepsMessageToken } from 'app/shared/model/preps/preps-message-token.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IPrepsMessageTokenProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const PrepsMessageToken = (props: IPrepsMessageTokenProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const { prepsMessageTokenList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="preps-message-token-heading">
        Preps Message Tokens
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp; Create new Preps Message Token
        </Link>
      </h2>
      <div className="table-responsive">
        {prepsMessageTokenList && prepsMessageTokenList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  ID <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('description')}>
                  Description <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('timeSent')}>
                  Time Sent <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('tokenValue')}>
                  Token Value <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('received')}>
                  Received <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('actioned')}>
                  Actioned <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('contentFullyEnqueued')}>
                  Content Fully Enqueued <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {prepsMessageTokenList.map((prepsMessageToken, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${prepsMessageToken.id}`} color="link" size="sm">
                      {prepsMessageToken.id}
                    </Button>
                  </td>
                  <td>{prepsMessageToken.description}</td>
                  <td>{prepsMessageToken.timeSent}</td>
                  <td>{prepsMessageToken.tokenValue}</td>
                  <td>{prepsMessageToken.received ? 'true' : 'false'}</td>
                  <td>{prepsMessageToken.actioned ? 'true' : 'false'}</td>
                  <td>{prepsMessageToken.contentFullyEnqueued ? 'true' : 'false'}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${prepsMessageToken.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${prepsMessageToken.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${prepsMessageToken.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Preps Message Tokens found</div>
        )}
      </div>
      {props.totalItems ? (
        <div className={prepsMessageTokenList && prepsMessageTokenList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ prepsMessageToken }: IRootState) => ({
  prepsMessageTokenList: prepsMessageToken.entities,
  loading: prepsMessageToken.loading,
  totalItems: prepsMessageToken.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PrepsMessageToken);
