// src/main/webapp/app/entities/preps/preps-file-upload/preps-file-upload-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { ICrudGetAction, ICrudGetAllAction, setFileData, openFile, byteSize, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, setBlob, reset } from './preps-file-upload.reducer';
import { IPrepsFileUpload } from 'app/shared/model/preps/preps-file-upload.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IPrepsFileUploadUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PrepsFileUploadUpdate = (props: IPrepsFileUploadUpdateProps) => {
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { prepsFileUploadEntity, loading, updating } = props;

  const { dataFile, dataFileContentType } = prepsFileUploadEntity;

  const handleClose = () => {
    props.history.push('/preps-file-upload' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  const onBlobChange = (isAnImage, name) => event => {
    setFileData(event, (contentType, data) => props.setBlob(name, data, contentType), isAnImage);
  };

  const clearBlob = name => () => {
    props.setBlob(name, undefined, undefined);
  };

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...prepsFileUploadEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="prepaymentsDevApp.prepsPrepsFileUpload.home.createOrEditLabel">Create or edit a PrepsFileUpload</h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : prepsFileUploadEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="preps-file-upload-id">ID</Label>
                  <AvInput id="preps-file-upload-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="descriptionLabel" for="preps-file-upload-description">
                  Description
                </Label>
                <AvField
                  id="preps-file-upload-description"
                  type="text"
                  name="description"
                  validate={{
                    required: { value: true, errorMessage: 'This field is required.' },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="fileNameLabel" for="preps-file-upload-fileName">
                  File Name
                </Label>
                <AvField
                  id="preps-file-upload-fileName"
                  type="text"
                  name="fileName"
                  validate={{
                    required: { value: true, errorMessage: 'This field is required.' },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <Label id="periodFromLabel" for="preps-file-upload-periodFrom">
                  Period From
                </Label>
                <AvField id="preps-file-upload-periodFrom" type="date" className="form-control" name="periodFrom" />
              </AvGroup>
              <AvGroup>
                <Label id="periodToLabel" for="preps-file-upload-periodTo">
                  Period To
                </Label>
                <AvField id="preps-file-upload-periodTo" type="date" className="form-control" name="periodTo" />
              </AvGroup>
              <AvGroup>
                <Label id="prepsFileTypeIdLabel" for="preps-file-upload-prepsFileTypeId">
                  Preps File Type Id
                </Label>
                <AvField
                  id="preps-file-upload-prepsFileTypeId"
                  type="string"
                  className="form-control"
                  name="prepsFileTypeId"
                  validate={{
                    required: { value: true, errorMessage: 'This field is required.' },
                    number: { value: true, errorMessage: 'This field should be a number.' },
                  }}
                />
              </AvGroup>
              <AvGroup>
                <AvGroup>
                  <Label id="dataFileLabel" for="dataFile">
                    Data File
                  </Label>
                  <br />
                  {dataFile ? (
                    <div>
                      {dataFileContentType ? <a onClick={openFile(dataFileContentType, dataFile)}>Open</a> : null}
                      <br />
                      <Row>
                        <Col md="11">
                          <span>
                            {dataFileContentType}, {byteSize(dataFile)}
                          </span>
                        </Col>
                        <Col md="1">
                          <Button color="danger" onClick={clearBlob('dataFile')}>
                            <FontAwesomeIcon icon="times-circle" />
                          </Button>
                        </Col>
                      </Row>
                    </div>
                  ) : null}
                  <input id="file_dataFile" type="file" onChange={onBlobChange(false, 'dataFile')} />
                  <AvInput
                    type="hidden"
                    name="dataFile"
                    value={dataFile}
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' },
                    }}
                  />
                </AvGroup>
              </AvGroup>
              <AvGroup check>
                <Label id="uploadSuccessfulLabel">
                  <AvInput id="preps-file-upload-uploadSuccessful" type="checkbox" className="form-check-input" name="uploadSuccessful" />
                  Upload Successful
                </Label>
              </AvGroup>
              <AvGroup check>
                <Label id="uploadProcessedLabel">
                  <AvInput id="preps-file-upload-uploadProcessed" type="checkbox" className="form-check-input" name="uploadProcessed" />
                  Upload Processed
                </Label>
              </AvGroup>
              <AvGroup>
                <Label id="uploadTokenLabel" for="preps-file-upload-uploadToken">
                  Upload Token
                </Label>
                <AvField id="preps-file-upload-uploadToken" type="text" name="uploadToken" validate={{}} />
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/preps-file-upload" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  prepsFileUploadEntity: storeState.prepsFileUpload.entity,
  loading: storeState.prepsFileUpload.loading,
  updating: storeState.prepsFileUpload.updating,
  updateSuccess: storeState.prepsFileUpload.updateSuccess,
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  setBlob,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PrepsFileUploadUpdate);

// src/main/webapp/app/entities/preps/preps-file-upload/preps-file-upload-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { JhiDataUtils, JhiFileLoadError, JhiEventManager, JhiEventWithContent } from 'ng-jhipster';

import { IPrepsFileUpload, PrepsFileUpload } from 'app/shared/model/preps/preps-file-upload.model';
import { PrepsFileUploadService } from './preps-file-upload.service';
import { AlertError } from 'app/shared/alert/alert-error.model';

@Component({
  selector: 'gha-preps-file-upload-update',
  templateUrl: './preps-file-upload-update.component.html',
})
export class PrepsFileUploadUpdateComponent implements OnInit {
  isSaving = false;
  periodFromDp: any;
  periodToDp: any;

  editForm = this.fb.group({
    id: [],
    description: [null, [Validators.required]],
    fileName: [null, [Validators.required]],
    periodFrom: [],
    periodTo: [],
    prepsFileTypeId: [null, [Validators.required]],
    dataFile: [null, [Validators.required]],
    dataFileContentType: [],
    uploadSuccessful: [],
    uploadProcessed: [],
    uploadToken: [null, []],
  });

  constructor(
    protected dataUtils: JhiDataUtils,
    protected eventManager: JhiEventManager,
    protected prepsFileUploadService: PrepsFileUploadService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ prepsFileUpload }) => {
      this.updateForm(prepsFileUpload);
    });
  }

  updateForm(prepsFileUpload: IPrepsFileUpload): void {
    this.editForm.patchValue({
      id: prepsFileUpload.id,
      description: prepsFileUpload.description,
      fileName: prepsFileUpload.fileName,
      periodFrom: prepsFileUpload.periodFrom,
      periodTo: prepsFileUpload.periodTo,
      prepsFileTypeId: prepsFileUpload.prepsFileTypeId,
      dataFile: prepsFileUpload.dataFile,
      dataFileContentType: prepsFileUpload.dataFileContentType,
      uploadSuccessful: prepsFileUpload.uploadSuccessful,
      uploadProcessed: prepsFileUpload.uploadProcessed,
      uploadToken: prepsFileUpload.uploadToken,
    });
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(contentType: string, base64String: string): void {
    this.dataUtils.openFile(contentType, base64String);
  }

  setFileData(event: any, field: string, isImage: boolean): void {
    this.dataUtils.loadFileToForm(event, this.editForm, field, isImage).subscribe(null, (err: JhiFileLoadError) => {
      this.eventManager.broadcast(
        new JhiEventWithContent<AlertError>('prepaymentsDeveloperApp.error', { message: err.message })
      );
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const prepsFileUpload = this.createFromForm();
    if (prepsFileUpload.id !== undefined) {
      this.subscribeToSaveResponse(this.prepsFileUploadService.update(prepsFileUpload));
    } else {
      this.subscribeToSaveResponse(this.prepsFileUploadService.create(prepsFileUpload));
    }
  }

  private createFromForm(): IPrepsFileUpload {
    return {
      ...new PrepsFileUpload(),
      id: this.editForm.get(['id'])!.value,
      description: this.editForm.get(['description'])!.value,
      fileName: this.editForm.get(['fileName'])!.value,
      periodFrom: this.editForm.get(['periodFrom'])!.value,
      periodTo: this.editForm.get(['periodTo'])!.value,
      prepsFileTypeId: this.editForm.get(['prepsFileTypeId'])!.value,
      dataFileContentType: this.editForm.get(['dataFileContentType'])!.value,
      dataFile: this.editForm.get(['dataFile'])!.value,
      uploadSuccessful: this.editForm.get(['uploadSuccessful'])!.value,
      uploadProcessed: this.editForm.get(['uploadProcessed'])!.value,
      uploadToken: this.editForm.get(['uploadToken'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IPrepsFileUpload>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="gha-preps-file-upload-heading">Create or edit a Preps File Upload</h2>

            <div>
                <gha-alert-error></gha-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_description">Description</label>
                    <input type="text" class="form-control" name="description" id="field_description"
                           formControlName="description"/>
                    <div *ngIf="editForm.get('description')!.invalid && (editForm.get('description')!.dirty || editForm.get('description')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('description')?.errors?.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_fileName">File Name</label>
                    <input type="text" class="form-control" name="fileName" id="field_fileName"
                           formControlName="fileName"/>
                    <div *ngIf="editForm.get('fileName')!.invalid && (editForm.get('fileName')!.dirty || editForm.get('fileName')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('fileName')?.errors?.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_periodFrom">Period From</label>
                    <div class="input-group">
                        <input id="field_periodFrom" type="text" class="form-control" name="periodFrom" ngbDatepicker #periodFromDp="ngbDatepicker" formControlName="periodFrom"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="periodFromDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_periodTo">Period To</label>
                    <div class="input-group">
                        <input id="field_periodTo" type="text" class="form-control" name="periodTo" ngbDatepicker #periodToDp="ngbDatepicker" formControlName="periodTo"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="periodToDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_prepsFileTypeId">Preps File Type Id</label>
                    <input type="number" class="form-control" name="prepsFileTypeId" id="field_prepsFileTypeId"
                           formControlName="prepsFileTypeId"/>
                    <div *ngIf="editForm.get('prepsFileTypeId')!.invalid && (editForm.get('prepsFileTypeId')!.dirty || editForm.get('prepsFileTypeId')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('prepsFileTypeId')?.errors?.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('prepsFileTypeId')?.errors?.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_dataFile">Data File</label>
                    <div>
                        <div *ngIf="editForm.get('dataFile')!.value" class="form-text text-danger clearfix">
                            <a class="pull-left" (click)="openFile(editForm.get('dataFileContentType')!.value, editForm.get('dataFile')!.value)">open</a><br>
                            <span class="pull-left">{{ editForm.get('dataFileContentType')!.value }}, {{ byteSize(editForm.get('dataFile')!.value) }}</span>
                            <button type="button" (click)="editForm.patchValue({dataFile: null});editForm.patchValue({dataFileContentType: null});"
                                    class="btn btn-secondary btn-xs pull-right">
                                <fa-icon icon="times"></fa-icon>
                            </button>
                        </div>
                        <input type="file" id="file_dataFile" (change)="setFileData($event, 'dataFile', false)"/>
                    </div>
                    <input type="hidden" class="form-control" name="dataFile" id="field_dataFile"
                           formControlName="dataFile"/>
                    <input type="hidden" class="form-control" name="dataFileContentType" id="field_dataFileContentType"
                           formControlName="dataFileContentType" />
                    <div *ngIf="editForm.get('dataFile')!.invalid && (editForm.get('dataFile')!.dirty || editForm.get('dataFile')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('dataFile')?.errors?.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_uploadSuccessful">Upload Successful</label>
                    <input type="checkbox" class="form-control" name="uploadSuccessful" id="field_uploadSuccessful"
                           formControlName="uploadSuccessful"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_uploadProcessed">Upload Processed</label>
                    <input type="checkbox" class="form-control" name="uploadProcessed" id="field_uploadProcessed"
                           formControlName="uploadProcessed"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_uploadToken">Upload Token</label>
                    <input type="text" class="form-control" name="uploadToken" id="field_uploadToken"
                           formControlName="uploadToken"/>
                    <div *ngIf="editForm.get('uploadToken')!.invalid && (editForm.get('uploadToken')!.dirty || editForm.get('uploadToken')!.touched)">
                    </div>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
