// src/main/webapp/app/entities/preps/preps-file-upload/preps-file-upload.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, ParamMap, Router, Data } from '@angular/router';
import { Subscription, combineLatest } from 'rxjs';
import { JhiEventManager, JhiDataUtils } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IPrepsFileUpload } from 'app/shared/model/preps/preps-file-upload.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { PrepsFileUploadService } from './preps-file-upload.service';
import { PrepsFileUploadDeleteDialogComponent } from './preps-file-upload-delete-dialog.component';

@Component({
  selector: 'gha-preps-file-upload',
  templateUrl: './preps-file-upload.component.html',
})
export class PrepsFileUploadComponent implements OnInit, OnDestroy {
  prepsFileUploads?: IPrepsFileUpload[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected prepsFileUploadService: PrepsFileUploadService,
    protected activatedRoute: ActivatedRoute,
    protected dataUtils: JhiDataUtils,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number, dontNavigate?: boolean): void {
    const pageToLoad: number = page || this.page || 1;

    this.prepsFileUploadService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<IPrepsFileUpload[]>) => this.onSuccess(res.body, res.headers, pageToLoad, !dontNavigate),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.handleNavigation();
    this.registerChangeInPrepsFileUploads();
  }

  protected handleNavigation(): void {
    combineLatest(this.activatedRoute.data, this.activatedRoute.queryParamMap, (data: Data, params: ParamMap) => {
      const page = params.get('page');
      const pageNumber = page !== null ? +page : 1;
      const sort = (params.get('sort') ?? data['defaultSort']).split(',');
      const predicate = sort[0];
      const ascending = sort[1] === 'asc';
      if (pageNumber !== this.page || predicate !== this.predicate || ascending !== this.ascending) {
        this.predicate = predicate;
        this.ascending = ascending;
        this.loadPage(pageNumber, true);
      }
    }).subscribe();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IPrepsFileUpload): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(contentType = '', base64String: string): void {
    return this.dataUtils.openFile(contentType, base64String);
  }

  registerChangeInPrepsFileUploads(): void {
    this.eventSubscriber = this.eventManager.subscribe('prepsFileUploadListModification', () => this.loadPage());
  }

  delete(prepsFileUpload: IPrepsFileUpload): void {
    const modalRef = this.modalService.open(PrepsFileUploadDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.prepsFileUpload = prepsFileUpload;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: IPrepsFileUpload[] | null, headers: HttpHeaders, page: number, navigate: boolean): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    if (navigate) {
      this.router.navigate(['/preps-file-upload'], {
        queryParams: {
          page: this.page,
          size: this.itemsPerPage,
          sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc'),
        },
      });
    }
    this.prepsFileUploads = data || [];
    this.ngbPaginationPage = this.page;
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page ?? 1;
  }
}

<div>
    <h2 id="page-heading">
        <span>Preps File Uploads</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-preps-file-upload" [routerLink]="['/preps-file-upload/new']">
            <fa-icon icon="plus"></fa-icon>
            <span>
            Create a new Preps File Upload
            </span>
        </button>
    </h2>

    <gha-alert-error></gha-alert-error>

    <gha-alert></gha-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="prepsFileUploads?.length === 0">
        <span>No prepsFileUploads found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="prepsFileUploads && prepsFileUploads.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span>ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="description"><span>Description</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="fileName"><span>File Name</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="periodFrom"><span>Period From</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="periodTo"><span>Period To</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="prepsFileTypeId"><span>Preps File Type Id</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="dataFile"><span>Data File</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="uploadSuccessful"><span>Upload Successful</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="uploadProcessed"><span>Upload Processed</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="uploadToken"><span>Upload Token</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let prepsFileUpload of prepsFileUploads ;trackBy: trackId">
                    <td><a [routerLink]="['/preps-file-upload', prepsFileUpload.id, 'view']">{{ prepsFileUpload.id }}</a></td>
                    <td>{{ prepsFileUpload.description }}</td>
                    <td>{{ prepsFileUpload.fileName }}</td>
                    <td>{{ prepsFileUpload.periodFrom | date:'mediumDate' }}</td>
                    <td>{{ prepsFileUpload.periodTo | date:'mediumDate' }}</td>
                    <td>{{ prepsFileUpload.prepsFileTypeId }}</td>
                    <td>
                        <a *ngIf="prepsFileUpload.dataFile" (click)="openFile(prepsFileUpload.dataFileContentType, prepsFileUpload.dataFile)">open</a>
                        <span *ngIf="prepsFileUpload.dataFile">{{ prepsFileUpload.dataFileContentType }}, {{ byteSize(prepsFileUpload.dataFile) }}</span>
                    </td>
                    <td>{{ prepsFileUpload.uploadSuccessful }}</td>
                    <td>{{ prepsFileUpload.uploadProcessed }}</td>
                    <td>{{ prepsFileUpload.uploadToken }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/preps-file-upload', prepsFileUpload.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/preps-file-upload', prepsFileUpload.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(prepsFileUpload)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="prepsFileUploads && prepsFileUploads.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/preps/preps-file-upload/preps-file-upload.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import {
  openFile,
  byteSize,
  ICrudGetAllAction,
  TextFormat,
  getSortState,
  IPaginationBaseState,
  JhiPagination,
  JhiItemCount,
} from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './preps-file-upload.reducer';
import { IPrepsFileUpload } from 'app/shared/model/preps/preps-file-upload.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IPrepsFileUploadProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const PrepsFileUpload = (props: IPrepsFileUploadProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const { prepsFileUploadList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="preps-file-upload-heading">
        Preps File Uploads
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp; Create new Preps File Upload
        </Link>
      </h2>
      <div className="table-responsive">
        {prepsFileUploadList && prepsFileUploadList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  ID <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('description')}>
                  Description <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('fileName')}>
                  File Name <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('periodFrom')}>
                  Period From <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('periodTo')}>
                  Period To <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('prepsFileTypeId')}>
                  Preps File Type Id <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataFile')}>
                  Data File <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('uploadSuccessful')}>
                  Upload Successful <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('uploadProcessed')}>
                  Upload Processed <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('uploadToken')}>
                  Upload Token <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {prepsFileUploadList.map((prepsFileUpload, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${prepsFileUpload.id}`} color="link" size="sm">
                      {prepsFileUpload.id}
                    </Button>
                  </td>
                  <td>{prepsFileUpload.description}</td>
                  <td>{prepsFileUpload.fileName}</td>
                  <td>
                    {prepsFileUpload.periodFrom ? (
                      <TextFormat type="date" value={prepsFileUpload.periodFrom} format={APP_LOCAL_DATE_FORMAT} />
                    ) : null}
                  </td>
                  <td>
                    {prepsFileUpload.periodTo ? (
                      <TextFormat type="date" value={prepsFileUpload.periodTo} format={APP_LOCAL_DATE_FORMAT} />
                    ) : null}
                  </td>
                  <td>{prepsFileUpload.prepsFileTypeId}</td>
                  <td>
                    {prepsFileUpload.dataFile ? (
                      <div>
                        {prepsFileUpload.dataFileContentType ? (
                          <a onClick={openFile(prepsFileUpload.dataFileContentType, prepsFileUpload.dataFile)}>Open &nbsp;</a>
                        ) : null}
                        <span>
                          {prepsFileUpload.dataFileContentType}, {byteSize(prepsFileUpload.dataFile)}
                        </span>
                      </div>
                    ) : null}
                  </td>
                  <td>{prepsFileUpload.uploadSuccessful ? 'true' : 'false'}</td>
                  <td>{prepsFileUpload.uploadProcessed ? 'true' : 'false'}</td>
                  <td>{prepsFileUpload.uploadToken}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${prepsFileUpload.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${prepsFileUpload.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${prepsFileUpload.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Preps File Uploads found</div>
        )}
      </div>
      {props.totalItems ? (
        <div className={prepsFileUploadList && prepsFileUploadList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ prepsFileUpload }: IRootState) => ({
  prepsFileUploadList: prepsFileUpload.entities,
  loading: prepsFileUpload.loading,
  totalItems: prepsFileUpload.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PrepsFileUpload);
