// src/main/webapp/app/entities/amortization-entry/amortization-entry-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './amortization-entry.reducer';
import { IAmortizationEntry } from 'app/shared/model/amortization-entry.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IAmortizationEntryUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const AmortizationEntryUpdate = (props: IAmortizationEntryUpdateProps) => {
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { amortizationEntryEntity, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/amortization-entry' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...amortizationEntryEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="prepaymentsDevApp.amortizationEntry.home.createOrEditLabel">Create or edit a AmortizationEntry</h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : amortizationEntryEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="amortization-entry-id">ID</Label>
                  <AvInput id="amortization-entry-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="accountNameLabel" for="amortization-entry-accountName">
                  Account Name
                </Label>
                <AvField id="amortization-entry-accountName" type="text" name="accountName" />
              </AvGroup>
              <AvGroup>
                <Label id="descriptionLabel" for="amortization-entry-description">
                  Description
                </Label>
                <AvField id="amortization-entry-description" type="text" name="description" />
              </AvGroup>
              <AvGroup>
                <Label id="accountNumberLabel" for="amortization-entry-accountNumber">
                  Account Number
                </Label>
                <AvField id="amortization-entry-accountNumber" type="text" name="accountNumber" />
              </AvGroup>
              <AvGroup>
                <Label id="expenseAccountNumberLabel" for="amortization-entry-expenseAccountNumber">
                  Expense Account Number
                </Label>
                <AvField id="amortization-entry-expenseAccountNumber" type="text" name="expenseAccountNumber" />
              </AvGroup>
              <AvGroup>
                <Label id="prepaymentNumberLabel" for="amortization-entry-prepaymentNumber">
                  Prepayment Number
                </Label>
                <AvField id="amortization-entry-prepaymentNumber" type="text" name="prepaymentNumber" />
              </AvGroup>
              <AvGroup>
                <Label id="prepaymentDateLabel" for="amortization-entry-prepaymentDate">
                  Prepayment Date
                </Label>
                <AvField id="amortization-entry-prepaymentDate" type="date" className="form-control" name="prepaymentDate" />
              </AvGroup>
              <AvGroup>
                <Label id="transactionAmountLabel" for="amortization-entry-transactionAmount">
                  Transaction Amount
                </Label>
                <AvField id="amortization-entry-transactionAmount" type="text" name="transactionAmount" />
              </AvGroup>
              <AvGroup>
                <Label id="amortizationDateLabel" for="amortization-entry-amortizationDate">
                  Amortization Date
                </Label>
                <AvField id="amortization-entry-amortizationDate" type="date" className="form-control" name="amortizationDate" />
              </AvGroup>
              <AvGroup>
                <Label id="uploadTokenLabel" for="amortization-entry-uploadToken">
                  Upload Token
                </Label>
                <AvField id="amortization-entry-uploadToken" type="text" name="uploadToken" />
              </AvGroup>
              <AvGroup>
                <Label id="prepaymentDataIdLabel" for="amortization-entry-prepaymentDataId">
                  Prepayment Data Id
                </Label>
                <AvField id="amortization-entry-prepaymentDataId" type="string" className="form-control" name="prepaymentDataId" />
              </AvGroup>
              <AvGroup>
                <Label id="compilationTokenLabel" for="amortization-entry-compilationToken">
                  Compilation Token
                </Label>
                <AvField id="amortization-entry-compilationToken" type="text" name="compilationToken" />
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/amortization-entry" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  amortizationEntryEntity: storeState.amortizationEntry.entity,
  loading: storeState.amortizationEntry.loading,
  updating: storeState.amortizationEntry.updating,
  updateSuccess: storeState.amortizationEntry.updateSuccess,
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(AmortizationEntryUpdate);

// src/main/webapp/app/entities/amortization-entry/amortization-entry-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IAmortizationEntry, AmortizationEntry } from 'app/shared/model/amortization-entry.model';
import { AmortizationEntryService } from './amortization-entry.service';

@Component({
  selector: 'gha-amortization-entry-update',
  templateUrl: './amortization-entry-update.component.html',
})
export class AmortizationEntryUpdateComponent implements OnInit {
  isSaving = false;
  prepaymentDateDp: any;
  amortizationDateDp: any;

  editForm = this.fb.group({
    id: [],
    accountName: [],
    description: [],
    accountNumber: [],
    expenseAccountNumber: [],
    prepaymentNumber: [],
    prepaymentDate: [],
    transactionAmount: [],
    amortizationDate: [],
    uploadToken: [],
    prepaymentDataId: [],
    compilationToken: [],
  });

  constructor(
    protected amortizationEntryService: AmortizationEntryService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ amortizationEntry }) => {
      this.updateForm(amortizationEntry);
    });
  }

  updateForm(amortizationEntry: IAmortizationEntry): void {
    this.editForm.patchValue({
      id: amortizationEntry.id,
      accountName: amortizationEntry.accountName,
      description: amortizationEntry.description,
      accountNumber: amortizationEntry.accountNumber,
      expenseAccountNumber: amortizationEntry.expenseAccountNumber,
      prepaymentNumber: amortizationEntry.prepaymentNumber,
      prepaymentDate: amortizationEntry.prepaymentDate,
      transactionAmount: amortizationEntry.transactionAmount,
      amortizationDate: amortizationEntry.amortizationDate,
      uploadToken: amortizationEntry.uploadToken,
      prepaymentDataId: amortizationEntry.prepaymentDataId,
      compilationToken: amortizationEntry.compilationToken,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const amortizationEntry = this.createFromForm();
    if (amortizationEntry.id !== undefined) {
      this.subscribeToSaveResponse(this.amortizationEntryService.update(amortizationEntry));
    } else {
      this.subscribeToSaveResponse(this.amortizationEntryService.create(amortizationEntry));
    }
  }

  private createFromForm(): IAmortizationEntry {
    return {
      ...new AmortizationEntry(),
      id: this.editForm.get(['id'])!.value,
      accountName: this.editForm.get(['accountName'])!.value,
      description: this.editForm.get(['description'])!.value,
      accountNumber: this.editForm.get(['accountNumber'])!.value,
      expenseAccountNumber: this.editForm.get(['expenseAccountNumber'])!.value,
      prepaymentNumber: this.editForm.get(['prepaymentNumber'])!.value,
      prepaymentDate: this.editForm.get(['prepaymentDate'])!.value,
      transactionAmount: this.editForm.get(['transactionAmount'])!.value,
      amortizationDate: this.editForm.get(['amortizationDate'])!.value,
      uploadToken: this.editForm.get(['uploadToken'])!.value,
      prepaymentDataId: this.editForm.get(['prepaymentDataId'])!.value,
      compilationToken: this.editForm.get(['compilationToken'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IAmortizationEntry>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="gha-amortization-entry-heading">Create or edit a Amortization Entry</h2>

            <div>
                <gha-alert-error></gha-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_accountName">Account Name</label>
                    <input type="text" class="form-control" name="accountName" id="field_accountName"
                           formControlName="accountName"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_description">Description</label>
                    <input type="text" class="form-control" name="description" id="field_description"
                           formControlName="description"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_accountNumber">Account Number</label>
                    <input type="text" class="form-control" name="accountNumber" id="field_accountNumber"
                           formControlName="accountNumber"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_expenseAccountNumber">Expense Account Number</label>
                    <input type="text" class="form-control" name="expenseAccountNumber" id="field_expenseAccountNumber"
                           formControlName="expenseAccountNumber"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_prepaymentNumber">Prepayment Number</label>
                    <input type="text" class="form-control" name="prepaymentNumber" id="field_prepaymentNumber"
                           formControlName="prepaymentNumber"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_prepaymentDate">Prepayment Date</label>
                    <div class="input-group">
                        <input id="field_prepaymentDate" type="text" class="form-control" name="prepaymentDate" ngbDatepicker #prepaymentDateDp="ngbDatepicker" formControlName="prepaymentDate"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="prepaymentDateDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_transactionAmount">Transaction Amount</label>
                    <input type="number" class="form-control" name="transactionAmount" id="field_transactionAmount"
                           formControlName="transactionAmount"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_amortizationDate">Amortization Date</label>
                    <div class="input-group">
                        <input id="field_amortizationDate" type="text" class="form-control" name="amortizationDate" ngbDatepicker #amortizationDateDp="ngbDatepicker" formControlName="amortizationDate"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="amortizationDateDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_uploadToken">Upload Token</label>
                    <input type="text" class="form-control" name="uploadToken" id="field_uploadToken"
                           formControlName="uploadToken"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_prepaymentDataId">Prepayment Data Id</label>
                    <input type="number" class="form-control" name="prepaymentDataId" id="field_prepaymentDataId"
                           formControlName="prepaymentDataId"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_compilationToken">Compilation Token</label>
                    <input type="text" class="form-control" name="compilationToken" id="field_compilationToken"
                           formControlName="compilationToken"/>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
