// src/main/webapp/app/entities/prepayment-entry/prepayment-entry-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IPrepaymentEntry } from 'app/shared/model/prepayment-entry.model';

@Component({
  selector: 'gha-prepayment-entry-detail',
  templateUrl: './prepayment-entry-detail.component.html',
})
export class PrepaymentEntryDetailComponent implements OnInit {
  prepaymentEntry: IPrepaymentEntry | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ prepaymentEntry }) => (this.prepaymentEntry = prepaymentEntry));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="prepaymentEntry">
            <h2><span>Prepayment Entry</span> {{ prepaymentEntry.id }}</h2>

            <hr>

            <gha-alert-error></gha-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span>Account Name</span></dt>
                <dd>
                    <span>{{ prepaymentEntry.accountName }}</span>
                </dd>
                <dt><span>Description</span></dt>
                <dd>
                    <span>{{ prepaymentEntry.description }}</span>
                </dd>
                <dt><span>Account Number</span></dt>
                <dd>
                    <span>{{ prepaymentEntry.accountNumber }}</span>
                </dd>
                <dt><span>Prepayment Number</span></dt>
                <dd>
                    <span>{{ prepaymentEntry.prepaymentNumber }}</span>
                </dd>
                <dt><span>Prepayment Date</span></dt>
                <dd>
                    <span>{{ prepaymentEntry.prepaymentDate }}</span>
                </dd>
                <dt><span>Transaction Amount</span></dt>
                <dd>
                    <span>{{ prepaymentEntry.transactionAmount }}</span>
                </dd>
                <dt><span>Upload Token</span></dt>
                <dd>
                    <span>{{ prepaymentEntry.uploadToken }}</span>
                </dd>
                <dt><span>Prepayment Data Id</span></dt>
                <dd>
                    <span>{{ prepaymentEntry.prepaymentDataId }}</span>
                </dd>
                <dt><span>Compilation Token</span></dt>
                <dd>
                    <span>{{ prepaymentEntry.compilationToken }}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/prepayment-entry', prepaymentEntry.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/prepayment-entry/prepayment-entry-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './prepayment-entry.reducer';
import { IPrepaymentEntry } from 'app/shared/model/prepayment-entry.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPrepaymentEntryDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PrepaymentEntryDetail = (props: IPrepaymentEntryDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { prepaymentEntryEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          PrepaymentEntry [<b>{prepaymentEntryEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="accountName">Account Name</span>
          </dt>
          <dd>{prepaymentEntryEntity.accountName}</dd>
          <dt>
            <span id="description">Description</span>
          </dt>
          <dd>{prepaymentEntryEntity.description}</dd>
          <dt>
            <span id="accountNumber">Account Number</span>
          </dt>
          <dd>{prepaymentEntryEntity.accountNumber}</dd>
          <dt>
            <span id="prepaymentNumber">Prepayment Number</span>
          </dt>
          <dd>{prepaymentEntryEntity.prepaymentNumber}</dd>
          <dt>
            <span id="prepaymentDate">Prepayment Date</span>
          </dt>
          <dd>
            {prepaymentEntryEntity.prepaymentDate ? (
              <TextFormat value={prepaymentEntryEntity.prepaymentDate} type="date" format={APP_LOCAL_DATE_FORMAT} />
            ) : null}
          </dd>
          <dt>
            <span id="transactionAmount">Transaction Amount</span>
          </dt>
          <dd>{prepaymentEntryEntity.transactionAmount}</dd>
          <dt>
            <span id="uploadToken">Upload Token</span>
          </dt>
          <dd>{prepaymentEntryEntity.uploadToken}</dd>
          <dt>
            <span id="prepaymentDataId">Prepayment Data Id</span>
          </dt>
          <dd>{prepaymentEntryEntity.prepaymentDataId}</dd>
          <dt>
            <span id="compilationToken">Compilation Token</span>
          </dt>
          <dd>{prepaymentEntryEntity.compilationToken}</dd>
        </dl>
        <Button tag={Link} to="/prepayment-entry" replace color="info">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/prepayment-entry/${prepaymentEntryEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ prepaymentEntry }: IRootState) => ({
  prepaymentEntryEntity: prepaymentEntry.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PrepaymentEntryDetail);
